micronaut:
  ssl:
    enabled: true
  server:
    ssl:
      enabled: true
      key-store:
        path: classpath:ssl/keystore.p12
        password: ZSE4zse4
        type: PKCS12
  application:
    name: micronaut-dictionary
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    url: jdbc:postgresql://${DB_HOST:192.168.1.72}:${DB_PORT:5432}/${DB_NAME:r2-dict-isn}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:ZSE4zse4}
r2dbc:
  datasources:
    default:
      dialect: POSTGRES
      db-type: postgres
      url: r2dbc:postgresql://${DB_HOST:192.168.1.72}:${DB_PORT:5432}/${DB_NAME:r2-dict-isn}
      username: ${DB_USERNAME:postgres}
      password: ${DB_PASSWORD:ZSE4zse4}
#flyway:
#  datasources:
#    default:
#      enabled: true
